# **PANDAS**

In [22]:
# How do you create a DataFrame from a dictionary and display the first few rows?

import pandas as pd

data = {'col1': [1, 2, 3, 4, 5], 'col2': [6, 7, 8, 9, 10], 'col3': [11, 12, 13, 14, 15]}

df = pd.DataFrame(data)

print('Full DataFrame:\n', df)
print('\nFirst 3 rows:\n', df.head(3))


Full DataFrame:
    col1  col2  col3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

First 3 rows:
    col1  col2  col3
0     1     6    11
1     2     7    12
2     3     8    13


In [24]:
# How do you filter a DataFrame to show only rows where the age is greater than 30?

import pandas as pd

data = {'name': ['Rakshit', 'Jishnu', 'Aditi', 'Aishwariya', 'Charan'], 'age': [22, 28, 31, 35, 29]}

df = pd.DataFrame(data)

filtered_df = df[df['age'] > 30]

filtered_df

name  age
2       Aditi   31
3  Aishwariya   35

In [37]:
# How do you group a DataFrame by a column and calculate the mean of another column?

import pandas as pd

data = {'Key': ['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D'],
        'Value': [10, 15, 20, 25, 30, 35, 40, 45]}
df = pd.DataFrame(data)

print('Original DataFrame:\n', df)

grouped_mean = df.groupby('Key')['Value'].mean()

print('\nMean of Value by Key:\n', grouped_mean)

Original DataFrame:
   Key  Value
0   A     10
1   A     15
2   B     20
3   B     25
4   C     30
5   C     35
6   D     40
7   D     45

Mean of Value by Key:
 Key
A    12.5
B    22.5
C    32.5
D    42.5
Name: Value, dtype: float64


In [40]:
# How do you add a new column to a DataFrame that contains the square of the ages?

import pandas as pd

data = {'name': ['Rakshit', 'Jishnu', 'Aditi', 'Aishwariya', 'Charan'], 'age': [22, 28, 31, 35, 29]}

df = pd.DataFrame(data)

df['age_squared'] = df['age'] ** 2

df

name  age  age_squared
0     Rakshit   22          484
1      Jishnu   28          784
2       Aditi   31          961
3  Aishwariya   35         1225
4      Charan   29          841

In [43]:
# How do you sort a DataFrame by a specific column in descending order?

import pandas as pd

data = {'Roll No': [1, 2, 3, 4, 5], 'Name': ['Rakshit', 'Ruchir', 'Jishnu', 'Vidit', 'Shrikant'], 'age': [22, 25, 27, 24, 29]}

df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Name', ascending=False)

sorted_df

Roll No      Name  age
3        4     Vidit   24
4        5  Shrikant   29
1        2    Ruchir   25
0        1   Rakshit   22
2        3    Jishnu   27

In [47]:
# How do you merge two DataFrames on a common column?

import pandas as pd

data1 = {'key': ['A', 'B', 'C', 'D'], 'value1': [1, 2, 3, 4]}
df1 = pd.DataFrame(data1)

data2 = {'key': ['B', 'C', 'E', 'F'], 'value2': [5, 6, 7, 8]}
df2 = pd.DataFrame(data2)

merged_df = pd.merge(df1, df2, on='key', how='inner')

merged_df

key  value1  value2
0   B       2       5
1   C       3       6

# **NUMPY**

In [48]:
# How do you create a NumPy array from a list and display its shape?

import numpy as np

my_list = [1, 2, 3, 4, 5]

my_array = np.array(my_list)

print(my_array)
print(my_array.shape)

[1 2 3 4 5]
(5,)


In [50]:
# How do you calculate the mean and standard deviation of a NumPy array?

import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

mean = np.mean(my_array)
std_dev = np.std(my_array)

print('Mean:', mean)
print('Standard Deviation:', std_dev)

Mean: 3.0
Standard Deviation: 1.4142135623730951


In [51]:
# How do you perform element-wise multiplication of two NumPy arrays?

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a * b

print(result)

[ 4 10 18]


In [53]:
# How do you create a 2D NumPy array (matrix) and access a specific element?

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = matrix[1, 2]

print("Matrix:\n", matrix)
print("\nElement at row 1, column 2:", element)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at row 1, column 2: 6


In [55]:
# How do you find the maximum and minimum values in a NumPy array?

arr = np.array([23, 87, 56, 51, 98, 65, 12])

max_value = np.max(arr)
min_value = np.min(arr)

print("Array:", arr)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Array: [23 87 56 51 98 65 12]
Maximum value: 98
Minimum value: 12


In [56]:
# How do you compute the dot product of two NumPy arrays?

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)

print('Dot Product:', dot_product)

Dot Product: 32
